# Generated by Django 5.2.3 on 2025-07-26 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_populate_classes'),
        ('teacher', '0003_populate_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubjectassignment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.schoolsection'),
        ),
    ]
