# Generated by Django 5.2.3 on 2025-07-24 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_populate_schoolboards'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'school_academic_year',
                'ordering': ['start_year', 'end_year'],
                'unique_together': {('start_year', 'end_year')},
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField()),
                ('chapter_name', models.CharField(max_length=200)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear')),
                ('school_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolboard')),
            ],
            options={
                'db_table': 'syllabus_chapter',
                'ordering': ['school_board', 'academic_year', 'chapter_number'],
                'abstract': False,
                'unique_together': {('school_board', 'academic_year', 'chapter_number')},
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='school.chapter')),
            ],
            options={
                'db_table': 'syllabus_prerequisite',
                'ordering': ['chapter', 'topic'],
                'abstract': False,
                'unique_together': {('chapter', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_topics', to='school.chapter')),
            ],
            options={
                'db_table': 'syllabus_sub_topic',
                'ordering': ['chapter', 'name'],
                'abstract': False,
                'unique_together': {('chapter', 'name')},
            },
        ),
    ]
