# Generated by Django 5.2.3 on 2025-07-24 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_chapter_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDefaultClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'db_table': 'school_default_classes',
            },
        ),
        migrations.CreateModel(
            name='SchoolDefaultSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'school_default_subjects',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolSyllabusEbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebook_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolboard')),
                ('class_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schooldefaultclasses')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schooldefaultsubjects')),
            ],
            options={
                'db_table': 'school_syllabus_ebooks',
                'unique_together': {('board', 'subject', 'class_number', 'ebook_name')},
            },
        ),
    ]
