# Generated by Django 5.2.3 on 2025-07-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_populate_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsyllabusebooks',
            name='ebook_type',
            field=models.CharField(choices=[('single', 'Single'), ('chapter_wise', 'Chapter Wise')], max_length=50, null=True),
        ),
    ]
