# Generated by Django 5.2.3 on 2025-07-26 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_populate_schoolboards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter_number']},
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('school_board', 'chapter_number')},
        ),
        migrations.AddField(
            model_name='chapter',
            name='ebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schoolsyllabusebooks'),
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='academic_year',
        ),
    ]
