# Generated by Django 5.2.3 on 2025-07-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_chapter_options_alter_chapter_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('chapter_number', 'ebook')},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='school_board',
        ),
    ]
