# Generated by Django 5.2.3 on 2025-07-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_chapter_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolboardmapping',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='schoolboardmapping',
            constraint=models.UniqueConstraint(fields=('school', 'board'), name='unique_school_board'),
        ),
    ]
