# Generated by Django 5.2.3 on 2025-07-26 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_classassignment_academic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'school_section',
            },
        ),
        migrations.RemoveConstraint(
            model_name='schoolclass',
            name='unique_class_number_section',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='section',
        ),
        migrations.AddField(
            model_name='schoolsection',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.schoolclass'),
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.schoolsection'),
        ),
        migrations.AddConstraint(
            model_name='schoolsection',
            constraint=models.UniqueConstraint(fields=('class_instance', 'section'), name='unique_class_instance_section'),
        ),
    ]
