# Generated by Django 5.2.3 on 2025-07-13 19:04

from django.conf import settings
from django.db import migrations
from django.core.management import call_command

def load_fixture(apps, schema_editor):
    
    db_name = getattr(settings, 'CURRENT_MIGRATION_DB', 'default')

    fixtures = ['roles.json']
    for fixture in fixtures:
        call_command('loaddata', fixture,database=db_name)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
