# Generated by Django 5.2.3 on 2025-07-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_academicyear_chapter_prerequisite_subtopic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['academic_year', 'chapter_number']},
        ),
    ]
