# Generated by Django 5.2.3 on 2025-07-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolacademicyear',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='schoolacademicyear',
            name='start_date',
        ),
        migrations.AddField(
            model_name='schoolacademicyear',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolacademicyear',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
