# Generated by Django 5.2.3 on 2025-07-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_academicyear_end_date_and_more'),
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolchapter',
            options={'ordering': ['academic_year', 'chapter_number']},
        ),
        migrations.RenameField(
            model_name='schoolchapter',
            old_name='school_board',
            new_name='school_board_id',
        ),
        migrations.AlterUniqueTogether(
            name='schoolchapter',
            unique_together={('school_board_id', 'academic_year', 'chapter_number')},
        ),
    ]
