# Generated by Django 5.2.3 on 2025-07-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0004_alter_schoolchapter_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schoolclassprerequisite',
            name='unique_chapter_topic_section',
        ),
        migrations.RemoveConstraint(
            model_name='schoolclasssubtopic',
            name='unique_chapter_name_section',
        ),
    ]
