# Generated by Django 5.2.3 on 2025-07-16 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('roll_number', models.CharField(max_length=20)),
                ('admission_date', models.DateField()),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(max_length=15)),
                ('parent_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_list',
                'constraints': [models.UniqueConstraint(fields=('student_id', 'roll_number'), name='unique_student_id_roll_number')],
            },
        ),
        migrations.CreateModel(
            name='StudentClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolacademicyear')),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'student_class_assignment',
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_student_academic_year')],
            },
        ),
    ]
