# Generated by Django 5.2.3 on 2025-07-24 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_remove_academicyear_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField()),
                ('chapter_name', models.CharField(max_length=200)),
                ('school_board', models.IntegerField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolacademicyear')),
            ],
            options={
                'db_table': 'syllabus_chapter',
                'ordering': ['school_board', 'academic_year', 'chapter_number'],
                'abstract': False,
                'unique_together': {('school_board', 'academic_year', 'chapter_number')},
            },
        ),
        migrations.CreateModel(
            name='SchoolPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='syllabus.schoolchapter')),
            ],
            options={
                'db_table': 'syllabus_prerequisite',
                'ordering': ['chapter', 'topic'],
                'abstract': False,
                'unique_together': {('chapter', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='SchoolSubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_topics', to='syllabus.schoolchapter')),
            ],
            options={
                'db_table': 'syllabus_sub_topic',
                'ordering': ['chapter', 'name'],
                'abstract': False,
                'unique_together': {('chapter', 'name')},
            },
        ),
    ]
