# Generated by Django 5.2.3 on 2025-07-26 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_classassignment_academic_year'),
        ('syllabus', '0002_alter_schoolchapter_options_and_more'),
        ('teacher', '0003_populate_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolchapter',
            options={'ordering': ['chapter_number']},
        ),
        migrations.AddField(
            model_name='schoolchapter',
            name='class_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.schoolclass'),
        ),
        migrations.AddField(
            model_name='schoolchapter',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.subject'),
        ),
    ]
