# Generated by Django 5.2.3 on 2025-07-29 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_academicyear_end_date_and_more'),
        ('classes', '0007_populate_classes'),
        ('syllabus', '0003_alter_schoolchapter_options_and_more'),
        ('teacher', '0004_alter_teachersubjectassignment_school_class'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolchapter',
            unique_together={('school_board_id', 'academic_year', 'chapter_number', 'class_number', 'subject')},
        ),
        migrations.CreateModel(
            name='SchoolClassPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus.schoolchapter')),
                ('class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.schoolsection')),
            ],
            options={
                'db_table': 'classwise_prerequisite',
                'ordering': ['chapter', 'topic'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('chapter', 'topic', 'class_section'), name='unique_chapter_topic_section')],
            },
        ),
        migrations.CreateModel(
            name='SchoolClassSubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus.schoolchapter')),
                ('class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.schoolsection')),
            ],
            options={
                'db_table': 'classwise_sub_topic',
                'ordering': ['chapter', 'name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('chapter', 'name', 'class_section'), name='unique_chapter_name_section')],
            },
        ),
    ]
