# Generated by Django 5.2.3 on 2025-07-26 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_schoolsection_and_more'),
        ('student', '0003_alter_studentclassassignment_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassassignment',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.schoolsection'),
        ),
    ]
