# Generated by Django 5.2.3 on 2025-07-24 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_academicyear_end_date_and_more'),
        ('classes', '0004_remove_schoolclass_unique_name_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolacademicyear'),
        ),
    ]
