# Generated by Django 5.2.3 on 2025-07-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_populate_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsection',
            name='board_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
