# Generated by Django 5.2.3 on 2025-07-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_classassignment_class_teacher'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schoolclass',
            name='unique_name_section',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='name',
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='class_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(fields=('class_number', 'section'), name='unique_class_number_section'),
        ),
    ]
